name: Daily Scraper

on:
  schedule:
    - cron: '0 0 * * *'  # setiap hari jam 00:00 UTC
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install
        env:
          PUPPETEER_SKIP_DOWNLOAD: "true"  

      - name: Run scraper
        run: npm run scrape

      - name: Commit scraped JSON
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add public/users.json
          git commit -m "Update users.json" || echo "No changes"
          git push