name: Daily Scraper

on:
  schedule:
    - cron: '0 0 * * *'  # Setiap hari jam 00:00 UTC
  workflow_dispatch:  # Memungkinkan menjalankan secara manual juga

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run Puppeteer Scraper
        run: npm run scrape  # Menjalankan skrip scrape.js

      - name: Commit scraped JSON
        run: |
          git config user.name "revansp"
          git config user.email "revanspstudy28@gmail.com"
          git add public/users.json
          git commit -m "Update users.json" || echo "No changes"
          git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }}.git HEAD:${{ github.ref }}
